In [1]:
3 + 5 *4

23

In [2]:
weight_kg=60

In [4]:
print(weight_kg)
weight_kg**2

60


3600

In [5]:
my_number=3
my_float=2.43434434
my_string="This is my string"

In [7]:
print(my_string, my_float)

This is my string 2.43434434


In [9]:
weight_kg_text='weight in kilograms:'
print(weight_kg_text, weight_kg)
print('weight in pounds:', weight_kg*2.2)
weight_kg=100
print(weight_kg)

weight in kilograms: 60
weight in pounds: 132.0
100


In [10]:
x=5
y=6
print(x+y)

11


In [11]:
x=y
print(x+y)

12


In [12]:
mass=47.5
age=122
mass=mass*2.0
age=age-20
print(mass, age)

95.0 102


In [14]:
first, second = 'Grace', 'Shawn'
third, fourth = second, first
print(third, fourth)

Shawn Grace


In [15]:
import numpy

In [20]:
numpy.loadtxt(fname='week-four/inflammation-01.csv', delimiter=',')

array([[0., 0., 1., ..., 3., 0., 0.],
       [0., 1., 2., ..., 1., 0., 1.],
       [0., 1., 1., ..., 2., 1., 1.],
       ...,
       [0., 0., 1., ..., 3., 0., 0.],
       [0., 1., 2., ..., 1., 0., 1.],
       [0., 1., 1., ..., 2., 1., 1.]])

In [21]:
print(medical_data)

NameError: name 'medical_data' is not defined

In [22]:
medical_data=numpy.loadtxt(fname='week-four/inflammation-01.csv', delimiter=',')

In [23]:
print(medical_data)

[[0. 0. 1. ... 3. 0. 0.]
 [0. 1. 2. ... 1. 0. 1.]
 [0. 1. 1. ... 2. 1. 1.]
 ...
 [0. 0. 1. ... 3. 0. 0.]
 [0. 1. 2. ... 1. 0. 1.]
 [0. 1. 1. ... 2. 1. 1.]]


In [24]:
print(type(medical_data))

<class 'numpy.ndarray'>


In [25]:
a=[1,2,3,4]

In [26]:
print(a)

[1, 2, 3, 4]


In [27]:
print(a[0])

1


In [28]:
print(medical_data.dtype)

float64


In [30]:
print(medical_data.shape)
#rows,columns

(54, 40)


In [31]:
print('first value in medical data:', medical_data[0,0])

first value in medical data: 0.0


In [32]:
print('middle value in data', medical_data[30,20])

middle value in data 6.0


In [33]:
print(medical_data[0:4, 0:10])

[[0. 0. 1. 3. 1. 2. 4. 7. 8. 3.]
 [0. 1. 2. 1. 2. 1. 3. 2. 2. 6.]
 [0. 1. 1. 3. 3. 2. 6. 2. 5. 9.]
 [0. 0. 1. 3. 1. 2. 4. 7. 8. 3.]]


In [34]:
bruin=medical_data[:3, 36:]
print(bruin)

[[2. 3. 0. 0.]
 [1. 1. 0. 1.]
 [2. 2. 1. 1.]]


In [36]:
print(numpy.mean(medical_data))

5.658333333333333


In [37]:
import time

In [38]:
print(time.ctime())

Mon Jan 27 09:42:23 2020


In [39]:
maxval, minval = numpy.max(medical_data), numpy.min(medical_data)

In [40]:
print('max:',maxval, ',min:' ,minval,'')

max: 19.0 ,min: 0.0 


In [41]:
patient_0=medical_data[0,:]
print(patient_0)

[ 0.  0.  1.  3.  1.  2.  4.  7.  8.  3.  3.  3. 10.  5.  7.  4.  7.  7.
 12. 18.  6. 13. 11. 11.  7.  7.  4.  6.  8.  8.  4.  4.  5.  7.  3.  4.
  2.  3.  0.  0.]


In [42]:
print('max inflammation for patient 0:', numpy.max(patient_0))

max inflammation for patient 0: 18.0


In [45]:
print(numpy.mean(medical_data, axis=1))

[5.45  5.425 6.1   5.45  5.425 6.1   5.45  5.425 6.1   5.45  5.425 6.1
 5.45  5.425 6.1   5.45  5.425 6.1   5.45  5.425 6.1   5.45  5.425 6.1
 5.45  5.425 6.1   5.45  5.425 6.1   5.45  5.425 6.1   5.45  5.425 6.1
 5.45  5.425 6.1   5.45  5.425 6.1   5.45  5.425 6.1   5.45  5.425 6.1
 5.45  5.425 6.1   5.45  5.425 6.1  ]


In [46]:
#writing a function
def my_func(name):
    print('Hello', name)

In [47]:
my_func("Kobe")

Hello Kobe


In [48]:
def square_minus(x):
    square=x*x
    square=square-2
    return(square)

In [49]:
square-3

NameError: name 'square' is not defined

In [50]:
square_minus(4)

14

In [51]:
zzz = square_minus(10)
print(zzz)

98
